/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Command =
  | {
      command: "teleport";
      x: number;
      y: number;
      map: string;
    }
  | {
      command: "say";
      msg: string | string[];
    };

export interface FullAgentConfig {
  states: {
    conditions: unknown[];
    aspect?: {
      spritesheet: string;
      frameHeight: number;
      frameWidth: number;
      depth: number;
      collide: "try" | "no" | "immovable";
      movementSpeed: number;
      stepDuration: number;
      path: string;
    };
    on_interact?: Command[];
    on_touch?: Command[];
    on_init?: Command[];
  }[];
}
