/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GameGlobalConfig {
  gameTitle: string;
  gameScreenWidth: number;
  gameScreenHeight: number;
  playerSpritesheet: string;
  startX: number;
  startY: number;
  initialWorld: string;
  playerSpriteHeight?: number;
  playerSpriteWidth?: number;
  backend?: string;
  tileHeight?: number;
  tileWidth?: number;
}
